
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[261] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       63,   59,   39,   41,   62,   60,   59,   59,   59,   59,
       59,   24,   59,   39,   42,   11,   45,   43,   47,   49,
        9,   56,   57,   46,   56,   44,   48,   56,   56,   56,
       56,   56,   11,   45,   43,   47,   49,   52,   53,   52,
       52,   52,   52,   52,   52,   52,   42,   11,   45,   43,
       47,   49,   49,   58,   58,   58,   15,   58,   16,   58,
       58,   58,   58,   42,   11,   45,   43,   15,   16,   54,
       54,   19,   54,   54,   54,   54,   54,   42,   11,   45,

       43,   47,   49,   55,   55,   20,   55,   55,   55,   55,
       55,   55,   42,   11,   45,   43,   47,   49,   61,   61,
       18,   17,   61,   61,   61,   61,   61,   11,   45,   43,
       47,   49,    3,    3,    5,    5,   59,   10,   35,    0,
       59,   22,   23,   31,    7,   12,   13,    8,   14,   32,
       40,    0,   11,   45,   43,   47,   49,    9,   56,   46,
       44,   48,   56,   45,   43,   47,   49,   52,   52,   51,
        0,   52,    0,   52,   45,   43,   47,   49,   58,   15,
       15,   58,   16,   58,   11,   45,   43,   15,   54,   19,
       54,   54,   11,   45,   43,   47,   55,   20,   55,   55,

       11,   45,   43,   47,   61,   61,   10,   61,   61,   22,
       23,   31,   32,   11,   45,   43,   47,   49,    3,    3,
        5,    0,   10,   38,   34,    0,    1,   21,   29,    7,
       12,   13,    8,   30,   50,    0,   10,   61,    1,   21,
       29,   30,    3,    6,   37,   37,    4,   27,   28,    4,
       27,   28,    2,   33,   25,   26,   25,   26,   36,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    1,    1,    9,    1,
        1,   10,   11,    1,   12,    1,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
       17,   18,    1,    1,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       20,    1,   21,    1,   22,    1,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   23,   24,   25,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[26] =
    {   0,
        1,    2,    3,    4,    5,    6,    7,    1,    6,    1,
        1,    8,    1,    1,    5,    9,   10,    9,    5,    6,
        6,    5,    6,    4,    6
    } ;

static yyconst flex_int16_t yy_base[277] =
    {   0,
        0,   23,   47,   70,   94,  117,  672,  671,  141,  164,
      186,  211,  236,  259,  283,  306,   27,   29,   24,   32,
      687,    0,  690,  690,  690,  680,  676,  172,  664,  662,
       18,  320,  657,  690,   34,   76,   72,   81,   86,  664,
      675,    0,  673,   87,  669,   88,  119,  179,  657,  655,
      105,  650,  125,  131,  133,  135,  657,    0,  667,  663,
      314,  343,  651,  649,  152,  644,  168,  177,  175,  182,
      192,  651,  650,    0,  660,  656,  659,  320,  658,  642,
      640,  176,  635,  198,  199,  261,  266,  268,   29,    0,
      653,  270,  321,  638,  636,  254,  631,  277,  312,  308,

      317,  336,  638,    0,  648,  648,  643,  323,  631,  629,
      301,  617,  346,  347,  352,  353,  354,  615,  617,  356,
      690,  608,  358,  345,  361,  362,  363,  364,  369,  371,
      373,  191,    0,  595,    0,  581,    0,  587,  582,  576,
      373,  572,  690,  562,  579,  574,  331,  572,  690,  551,
      690,  378,  567,  382,  387,  388,  554,  563,    0,  392,
      393,  394,  394,  399,  400,  401,  548,    0,  401,  690,
      560,  545,  417,  405,  409,  411,  413,  540,    0,  550,
      549,  411,  545,  420,  542,  422,  426,  428,    0,  540,
      420,  432,  539,  434,  438,  439,    0,  534,  436,  442,

      532,  444,  446,  448,  531,  497,  496,  447,  455,  450,
      495,  452,  451,  494,  456,  461,  462,  463,    0,   65,
        0,  480,  490,  690,  485,  481,  690,  690,  469,  486,
      485,  484,  483,  462,  690,  467,  427,  472,  404,  375,
      473,  457,  467,  690,  690,  306,  690,  258,  247,  163,
      474,  478,  690,    0,  690,  690,  134,  121,  690,  690,
      503,  513,  523,  533,  541,  551,  559,  565,  573,  581,
      589,  599,  609,  619,  629,  639
    } ;

static yyconst flex_int16_t yy_def[277] =
    {   0,
      260,    1,  260,    3,  260,    5,    5,    6,  260,    9,
      261,  260,  260,   13,  260,   15,  262,  262,  263,  263,
      260,  264,  260,  260,  260,  260,  264,  264,  264,  264,
      264,  260,  264,  260,  260,  260,  260,  260,  260,  260,
       32,  265,  260,  260,  265,  260,  260,  265,  265,  265,
      265,  265,  260,  260,  260,  260,  265,  266,  260,  266,
      266,  266,  266,  266,  266,  266,  266,  260,  266,  266,
      266,   62,  266,  267,  267,  267,  268,  267,  260,  267,
      267,  267,  267,  267,  267,  267,  267,  268,  260,  269,
      269,  260,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  269,  270,  270,  260,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  271,  271,
      260,  260,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  272,  272,  273,  273,  264,  260,  274,  260,
       28,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  265,  260,
      260,  260,   48,  260,  260,  260,  265,  266,   61,  260,
      260,   62,  260,  266,  266,  266,  266,  173,  267,  260,
      268,   78,  260,  267,  267,  267,  267,  260,  269,  260,
       93,  269,  269,  269,  269,  269,  270,  260,  108,  270,

      270,  270,  270,  270,  271,  260,  271,  271,  271,  271,
      271,  271,  271,  260,  260,  260,  260,  271,  272,  272,
      273,  260,  260,  260,  275,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  271,  271,  271,
      271,  271,  272,  260,  260,  260,  260,  260,  260,  271,
      271,  271,  260,  276,  260,  260,  271,  271,  260,    0,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260
    } ;

static yyconst flex_int16_t yy_nxt[716] =
    {   0,
       22,   22,   23,   24,   25,   26,   22,   25,   27,   25,
       22,   22,   22,   22,   25,   28,   25,   22,   22,   29,
       30,   22,   31,   32,   33,   34,   25,   35,   36,   25,
       37,   25,   38,  183,   25,  136,  151,   39,  152,   40,
      144,  145,  134,  136,  134,  157,   41,   42,   42,   23,
       24,   25,   43,   42,   44,   45,   46,   42,   42,   42,
       42,   47,   48,   42,   42,   42,   49,   50,   42,   51,
       32,   52,   34,  154,   35,   53,  154,   54,  243,   55,
      153,  138,  155,  243,   56,  155,   57,  156,  160,  161,
      156,  160,  161,   41,   58,   58,   23,   24,   58,   59,

       58,   58,   60,   58,   58,   58,   58,   58,   58,   61,
       62,   58,   58,   63,   64,   58,   65,   32,   66,   34,
      162,   67,   68,  162,   69,  206,   70,  144,  145,  153,
      138,   71,  164,   72,  165,  164,  166,  165,  206,  166,
       41,   74,   74,   23,   24,   74,   75,   74,   74,   76,
       74,   74,   77,   74,   74,   77,   78,   79,   74,   77,
       80,   81,   77,   82,   32,   83,   34,  206,   84,   85,
      151,   86,  174,   87,  144,  145,  175,  140,   88,  175,
       89,  153,  138,  176,  140,  141,  176,   41,   23,   24,
      141,   91,  163,  177,   92,  206,  177,  163,  144,  145,

      151,   93,  184,  185,  138,   94,   95,  218,   96,   32,
       97,   90,   90,   34,   24,   98,   99,   90,  100,   92,
      101,   90,   90,   90,   90,  102,   93,  103,   90,   90,
       94,   95,   90,   96,   41,   97,  104,  104,   23,   24,
      104,  105,  106,  104,  107,  104,  104,  104,  104,  104,
      104,  108,  104,  104,  104,  109,  110,  104,  111,   32,
      112,   34,  186,  113,  114,  186,  115,  187,  116,  156,
      187,  256,  188,  117,  190,  118,  144,  145,  139,  151,
      255,  192,   41,  119,   25,   23,   24,   25,  120,  121,
      119,  122,  119,  119,  119,  119,  119,  119,  123,  119,

      119,  119,  124,  125,  119,  126,   32,  127,   34,  194,
       35,  128,  194,  129,  254,  130,  193,  138,  195,  140,
      131,  195,  132,  144,  145,  140,  140,  169,  140,   41,
      146,  147,  169,  182,  191,  232,  199,  196,  182,  191,
      196,  199,  147,  148,  149,  170,  171,  172,  151,  206,
      200,  201,  138,  202,  203,  204,  202,  203,  204,  173,
      206,  207,  206,  208,  210,  206,  206,  206,  214,  207,
      154,  209,  155,  215,  156,  216,  209,  217,  260,  206,
      151,  211,  152,  154,  212,  145,  154,  213,  155,  156,
      227,  155,  156,  160,  161,  162,  160,  161,  162,  260,

      164,  165,  166,  164,  165,  166,  260,  151,  206,  174,
      175,  227,  176,  175,  177,  176,  260,  177,  227,  170,
      171,  236,  151,  186,  184,  260,  186,  187,  227,  156,
      187,  237,  188,  173,  151,  194,  192,  227,  194,  195,
      196,  260,  195,  196,  151,  202,  200,  203,  202,  204,
      203,  206,  204,  227,  206,  206,  206,  154,  238,  206,
      215,  206,  155,  156,  240,  216,  217,  206,  209,  170,
      171,  236,  239,  209,  241,  242,  206,  206,  206,  218,
      243,  252,  206,  250,  253,  243,  249,  233,  232,  231,
      230,  248,  247,  246,  223,  251,  257,  244,  214,  206,

      237,  206,  258,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  137,  137,  206,  201,  137,  198,  137,
      137,  159,  159,  193,  190,  159,  185,  159,  159,  183,
      159,  168,  168,  180,  180,  168,  178,  168,  168,  179,
      179,  260,  235,  179,  167,  179,  179,  158,  179,  181,
      157,  153,  181,  189,  189,  234,  233,  189,  231,  189,
      189,  197,  197,  230,  229,  197,  228,  226,  197,  205,
      225,  223,  222,  205,  205,  205,  205,  205,  205,  219,

      219,  219,  219,  219,  219,  219,  219,  220,  219,  221,
      221,  221,  221,  221,  221,  221,  139,  221,  221,  224,
      224,  206,  224,  224,  224,  224,  224,  224,  224,  245,
      245,  157,  245,  245,  245,  245,  245,  245,  245,  259,
      259,  150,  259,  259,  259,  259,  259,  259,  259,  143,
      142,  139,  198,  138,  157,  150,  143,  142,  138,  150,
      143,  142,  183,  180,  139,  138,  157,  178,  150,  143,
      142,  139,  138,  167,  150,  143,  142,  139,  138,  158,
      157,  150,  143,  142,  139,  138,  260,   73,   58,   21,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,

      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260
    } ;

static yyconst flex_int16_t yy_chk[716] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,   19,    2,    2,   17,
        2,   18,    2,   89,   20,   19,   35,    2,   35,    2,
       31,   31,   17,   20,   18,   89,    2,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    4,   37,    4,    4,   37,    4,  220,    4,
       36,   36,   38,  220,    4,   38,    4,   39,   44,   46,
       39,   44,   46,    4,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    6,
       47,    6,    6,   47,    6,  258,    6,   51,   51,   53,
       53,    6,   54,    6,   55,   54,   56,   55,  257,   56,
        6,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,   10,  250,   10,   10,
       67,   10,   67,   10,   65,   65,   69,   28,   10,   69,
       10,   68,   68,   70,   48,   28,   70,   10,   11,   11,
       28,   11,   48,   71,   11,  132,   71,   48,   82,   82,

       84,   11,   84,   85,   85,   11,   11,  132,   11,   11,
       11,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   14,   86,   14,   14,   86,   14,   87,   14,   88,
       87,  249,   88,   14,   92,   14,   96,   96,   92,   98,
      248,   98,   14,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   16,  100,
       16,   16,  100,   16,  246,   16,   99,   99,  101,   61,
       16,  101,   16,  111,  111,   78,   93,   61,  108,   16,
       32,   32,   61,   78,   93,  147,  108,  102,   78,   93,
      102,  108,  147,   32,   32,   62,   62,   62,  113,  124,
      113,  114,  114,  115,  116,  117,  115,  116,  117,   62,
      120,  120,  123,  123,  124,  125,  126,  127,  128,  128,
      129,  123,  130,  129,  131,  130,  123,  131,  141,  240,
      152,  125,  152,  154,  126,  126,  154,  127,  155,  156,
      141,  155,  156,  160,  161,  162,  160,  161,  162,  163,

      164,  165,  166,  164,  165,  166,  169,  174,  239,  174,
      175,  163,  176,  175,  177,  176,  182,  177,  169,  173,
      173,  173,  184,  186,  184,  191,  186,  187,  182,  188,
      187,  237,  188,  173,  192,  194,  192,  191,  194,  195,
      196,  199,  195,  196,  200,  202,  200,  203,  202,  204,
      203,  208,  204,  199,  210,  213,  212,  215,  208,  209,
      215,  242,  216,  217,  210,  216,  217,  218,  209,  236,
      236,  236,  209,  209,  212,  213,  238,  241,  251,  218,
      243,  242,  252,  238,  243,  243,  234,  233,  232,  231,
      230,  229,  226,  225,  223,  241,  251,  222,  214,  211,

      207,  206,  252,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  264,  264,  205,  201,  264,  198,  264,
      264,  265,  265,  193,  190,  265,  185,  265,  265,  183,
      265,  266,  266,  181,  180,  266,  178,  266,  266,  267,
      267,  172,  171,  267,  167,  267,  267,  158,  267,  268,
      157,  153,  268,  269,  269,  150,  148,  269,  146,  269,
      269,  270,  270,  145,  144,  270,  142,  140,  270,  271,
      139,  138,  136,  271,  271,  271,  271,  271,  271,  272,

      272,  272,  272,  272,  272,  272,  272,  134,  272,  273,
      273,  273,  273,  273,  273,  273,  122,  273,  273,  274,
      274,  119,  274,  274,  274,  274,  274,  274,  274,  275,
      275,  118,  275,  275,  275,  275,  275,  275,  275,  276,
      276,  112,  276,  276,  276,  276,  276,  276,  276,  110,
      109,  107,  106,  105,  103,   97,   95,   94,   91,   83,
       81,   80,   79,   77,   76,   75,   73,   72,   66,   64,
       63,   60,   59,   57,   52,   50,   49,   45,   43,   41,
       40,   33,   30,   29,   27,   26,   21,    8,    7,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,

      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "wikilex.l"
#line 2 "wikilex.l"

/**
 **
 **  This file is part of the flex/bison-based parser for MediaWiki.
 **            This is the lexer - the input file for flex.
 **  See fb_defines.h on how to make it output debugging information.
 **
 ** This source file is licensed unter the GNU General Public License
 **               http://www.gnu.org/copyleft/gpl.html
 **                 Originally written 2004 by Timwi
 **/

#include <stdio.h>
#include <string.h>

/* This file defines debuglex and debuglex2. */
#include "fb_defines.h"

/* Notice: We need to include parsetree.h first because wikiparse.tab.h will
 * attempt to use the 'Node' type defined therein. */
#include "parsetree.h"
#include "wikiparse.tab.h"

/* Tells flex to stop processing input when EOF is reached. */
int yywrap(void) { return 1; }

int encodeTableRowInfo (char* input, int initleng)
{
    int i = 1;
    while (input[i] == '-') i++;
    return (((i-1) << 16) | (initleng-i));
}

#define COMMONTOKENS \
    if (YY_START != inattributeapo && YY_START != inattributeq && YY_START != canbeheading) \
        BEGIN (cannotbelistorheadingorpre);

#define APOSTROPHE_CATASTROPHE(len,debugstr,token)  \
    if (yytext[len] == '\'')                        \
    {                                               \
        yyless (1);                                 \
        yylval.node = newNodeS (TextToken, "'");    \
        debuglex2 ("TEXT(%s) ", "'");               \
        return TEXT;                                \
    }                                               \
    else                                            \
    {                                               \
        yyless (len);                               \
        debuglex (debugstr);                        \
        return token;                               \
    }

/* inclusive start conditions */


/* exclusive start conditions */

#line 754 "lex.yy.c"

#define INITIAL 0
#define canbelist 1
#define canbeheading 2
#define cannotbelistorheadingorpre 3
#define attributes 4
#define inattributeapo 5
#define inattributeq 6
#define startattribute 7
#define extension 8
#define comment 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 63 "wikilex.l"


    char* extension_name = 0;
    int i;


#line 926 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 261 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 690 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 69 "wikilex.l"
{
                                    fb_create_new_buffer (256); /* for the contents */
                                    i = strlen (yytext)-1;
                                    extension_name = (char*) malloc (i * sizeof (char));
                                    memcpy (extension_name, yytext + 1, --i);
                                    extension_name[i] = '\0';
                                    BEGIN (extension);
                                }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 77 "wikilex.l"
{
                                    i = strlen (extension_name);
                                    if (strncmp (extension_name, yytext+2, i))
                                        fb_write_to_buffer (yytext);
                                    else
                                    {
                                        BEGIN (cannotbelistorheadingorpre);
                                        yylval.node = newNodeN (ExtensionToken,
                                            extension_name, fb_get_buffer(), 0, 0);
                                        debuglex ("EXTENSION ");
                                        return EXTENSION;
                                    }
                                }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 90 "wikilex.l"
{   fb_write_to_buffer (yytext);    }
	YY_BREAK
case YY_STATE_EOF(extension):
#line 91 "wikilex.l"
{
                                    BEGIN (cannotbelistorheadingorpre);
                                    yylval.node = newNodeN (ExtensionToken,
                                        extension_name, fb_get_buffer(), 0, 0);
                                    debuglex ("EXTENSION ");
                                    return EXTENSION;
                                }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 99 "wikilex.l"
{ BEGIN (comment); debuglex ("BEGINCOMMENT "); return BEGINCOMMENT; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 100 "wikilex.l"
{ debuglex ("TEXT "); yylval.node = newNodeS (TextToken, strdup (yytext)); return TEXT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 101 "wikilex.l"
{ BEGIN (cannotbelistorheadingorpre); debuglex ("ENDCOMMENT "); return ENDCOMMENT; }
	YY_BREAK
/* For the table-related tokens, we need to remember enough information so that we can
     * reliably turn things back into text. */
case 7:
YY_RULE_SETUP
#line 105 "wikilex.l"
{ BEGIN(attributes); debuglex ("TABLEBEGIN ");   yylval.num = yyleng-2;       return TABLEBEGIN;    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 106 "wikilex.l"
{ BEGIN(attributes); debuglex ("TABLECELL ");    yylval.num = 2*(yyleng-2);   return TABLECELL;     }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 107 "wikilex.l"
{ BEGIN(attributes); debuglex ("TABLECELL ");    yylval.num = 2*(yyleng-1)+1; return TABLECELL;     }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 108 "wikilex.l"
{ BEGIN(attributes); debuglex ("TABLEHEAD ");    yylval.num = 2*(yyleng-2);   return TABLEHEAD;     }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 109 "wikilex.l"
{ BEGIN(attributes); debuglex ("TABLEHEAD ");    yylval.num = 2*(yyleng-1)+1; return TABLEHEAD;     }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "wikilex.l"
{ BEGIN(attributes); debuglex ("TABLECAPTION "); yylval.num = yyleng-2;       return TABLECAPTION;  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 111 "wikilex.l"
{ BEGIN(attributes); debuglex ("TABLEROW ");     yylval.num = encodeTableRowInfo (yytext, yyleng); return TABLEROW; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 112 "wikilex.l"
{ BEGIN(cannotbelistorheadingorpre); debuglex ("TABLEEND "); return TABLEEND; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 114 "wikilex.l"
{
        debuglex2 ("ATTRIBUTE(%s) ", yytext);
        yylval.ad = newAttributeDataFromStr (yytext);
        return ATTRIBUTE;
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "wikilex.l"
{
        debuglex2 ("EQUALS(%d) ", yyleng-1);
        yylval.num = yyleng-1;
        BEGIN (startattribute);
        return EQUALS;
    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 126 "wikilex.l"
{ BEGIN (inattributeapo); yylval.num = 0;        debuglex ("ATTRAPO(0) ");             return ATTRAPO; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 127 "wikilex.l"
{ BEGIN (inattributeq);   yylval.num = 0;        debuglex ("ATTRQ(0) ");               return ATTRQ;   }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 128 "wikilex.l"
{ BEGIN (attributes);     yylval.num = yyleng-1; debuglex2 ("ATTRAPO(%d) ", yyleng-1); return ATTRAPO; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 129 "wikilex.l"
{ BEGIN (attributes);     yylval.num = yyleng-1; debuglex2 ("ATTRQ(%d) ",   yyleng-1); return ATTRQ;   }
	YY_BREAK
/*
	http                { COMMONTOKENS; debuglex ("PROTOCOL "); return PROTOCOL ; }
	\:\/\/                { COMMONTOKENS; debuglex ("PROTOCOLSEP "); return PROTOCOLSEP ; }
	"\["                  { COMMONTOKENS; debuglex ("OPENEXTERNALLINK "); return OPENEXTERNALLINK ; }
	"\]"                  { COMMONTOKENS; debuglex ("CLOSEEXTERNALLINK "); return CLOSEEXTERNALLINK ; }
	[a-z]               { COMMONTOKENS; debuglex ("LINKTRAIL "); return LINKTRAIL; }*/
case 21:
YY_RULE_SETUP
#line 138 "wikilex.l"
{ COMMONTOKENS; debuglex ("OPENLINK "); return OPENLINK; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 139 "wikilex.l"
{ COMMONTOKENS; debuglex ("OPENDBLSQBR "); return OPENDBLSQBR; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 140 "wikilex.l"
{ COMMONTOKENS; debuglex ("CLOSEDBLSQBR "); return CLOSEDBLSQBR; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 141 "wikilex.l"
{ COMMONTOKENS; debuglex ("PIPE "); return PIPE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 142 "wikilex.l"
{ COMMONTOKENS; debuglex ("OPENPENTUPLECURLY "); return OPENPENTUPLECURLY; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 143 "wikilex.l"
{ COMMONTOKENS; debuglex ("CLOSEPENTUPLECURLY "); return CLOSEPENTUPLECURLY; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 144 "wikilex.l"
{ COMMONTOKENS; debuglex ("OPENTEMPLATE "); yyless (2); return OPENTEMPLATE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 145 "wikilex.l"
{ COMMONTOKENS; debuglex ("CLOSETEMPLATE "); yyless (2); return CLOSETEMPLATE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 146 "wikilex.l"
{ COMMONTOKENS; debuglex ("OPENTEMPLATEVAR "); return OPENTEMPLATEVAR; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 147 "wikilex.l"
{ COMMONTOKENS; debuglex ("CLOSETEMPLATEVAR "); return CLOSETEMPLATEVAR; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 148 "wikilex.l"
{ COMMONTOKENS; debuglex ("OPENTEMPLATE "); return OPENTEMPLATE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 149 "wikilex.l"
{ COMMONTOKENS; debuglex ("CLOSETEMPLATE "); return CLOSETEMPLATE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 150 "wikilex.l"
{ COMMONTOKENS; debuglex ("APO5 "); return APO5; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 151 "wikilex.l"
{ COMMONTOKENS; debuglex ("APO3 "); return APO3; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 152 "wikilex.l"
{ COMMONTOKENS; debuglex ("APO2 "); return APO2; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 153 "wikilex.l"
{ COMMONTOKENS; APOSTROPHE_CATASTROPHE (5, "APO5 ", APO5); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 154 "wikilex.l"
{ COMMONTOKENS; APOSTROPHE_CATASTROPHE (3, "APO3 ", APO3); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 155 "wikilex.l"
{ COMMONTOKENS; APOSTROPHE_CATASTROPHE (2, "APO2 ", APO2); }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 156 "wikilex.l"
{ BEGIN (INITIAL); debuglex ("NEWLINE\n"); return NEWLINE; }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 157 "wikilex.l"
{ BEGIN (INITIAL); debuglex ("NEWLINE\n"); return NEWLINE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 158 "wikilex.l"
{ /* ignore this one */ debuglex ("<13> "); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 160 "wikilex.l"
{ BEGIN(cannotbelistorheadingorpre); debuglex ("PRELINE "); return PRELINE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 161 "wikilex.l"
{ BEGIN(canbelist); debuglex ("LISTBULLET "); return LISTBULLET; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 162 "wikilex.l"
{ debuglex ("LISTBULLET "); return LISTBULLET; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 164 "wikilex.l"
{ BEGIN(canbelist); debuglex ("LISTNUMBERED "); return LISTNUMBERED; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 165 "wikilex.l"
{ debuglex ("LISTNUMBERED "); return LISTNUMBERED; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 167 "wikilex.l"
{ BEGIN(canbelist); debuglex ("LISTIDENT "); return LISTIDENT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 168 "wikilex.l"
{ debuglex ("LISTIDENT "); return LISTIDENT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 170 "wikilex.l"
{
                                    BEGIN (canbeheading);
                                    yylval.num = strlen (yytext);
                                    debuglex2 ("HEADING(%d) ", yylval.num);
                                    return HEADING;
                                }
	YY_BREAK
case 50:
/* rule 50 can match eol */
#line 177 "wikilex.l"
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 177 "wikilex.l"
{
                                    yylval.num = 0;
                                    while (yytext [ yylval.num ] == '=')
                                        yylval.num++;
                                    yylval.num |= (yyleng-yylval.num) << 16;
                                    debuglex2 ("ENDHEADING(%d) ", yylval.num);
                                    return ENDHEADING;
                                }
	YY_BREAK
case 52:
#line 187 "wikilex.l"
case 53:
#line 188 "wikilex.l"
case 54:
#line 190 "wikilex.l"
case 55:
YY_RULE_SETUP
#line 191 "wikilex.l"
{
    yylval.node = newNodeS (TextToken, strdup (yytext));
    debuglex2 ("TEXT(%s) ", yytext);
    return TEXT;                                                                    }
	YY_BREAK
case 56:
#line 197 "wikilex.l"
case 57:
#line 198 "wikilex.l"
case 58:
#line 200 "wikilex.l"
case 59:
#line 202 "wikilex.l"
case 60:
YY_RULE_SETUP
#line 202 "wikilex.l"
{
    BEGIN(cannotbelistorheadingorpre);
    yylval.node = newNodeS (TextToken, strdup (yytext));
    debuglex2 ("TEXT(%s) ", yytext);
    return TEXT;                                                                    }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 208 "wikilex.l"
{
    BEGIN (attributes);
    yylval.node = newNodeS (TextToken, strdup (yytext));
    debuglex2 ("TEXT(%s) ", yytext);
    return TEXT;                                                                    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 213 "wikilex.l"
ECHO;
	YY_BREAK
#line 1371 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(canbelist):
case YY_STATE_EOF(canbeheading):
case YY_STATE_EOF(cannotbelistorheadingorpre):
case YY_STATE_EOF(attributes):
case YY_STATE_EOF(inattributeapo):
case YY_STATE_EOF(inattributeq):
case YY_STATE_EOF(startattribute):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 261 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 261 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 260);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 213 "wikilex.l"



